# Вычисление показателей для региона (на 3 уровнях) и для подаваемой территории

In [2]:
# Импорты

import sys
sys.path.append('../')
import transport_frames.src.graph_builder.criteria as criteria
import transport_frames.src.metrics.indicators as indicators
import transport_frames.src.metrics.grade_territory as grade_territory
import transport_frames.src.graph_builder.graphbuilder as graphbuilder
import momepy
import osmnx as ox
import geopandas as gpd
import shapely
import pandas as pd
import networkx as nx
import numpy as np
from shapely import wkt

/Users/sashamorozov/Documents/Code/NCCR/transport_frames/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# CRS (в формате ESPG) и OSM ID (id полигона региона, id точки админ. центра региона) по тестовым регионам

# Ленинградская_область EPSG: 32636  / 176095 / N27025179 (Гатчина)
# Санкт_Петербург EPSG:32636 / 337422 / N27490597
# Москва EPSG:32637 / 102269 / N1686293227
# Волгоградская_область EPSG:32638 / 77665 /  N27504363
# Тульская_область EPSG:32637 /  81993 / N34389350
# Омская_область EPSG:32643 / 140292 /  N27503946
# Краснодарский_край EPSG:32637 / 108082 / N27505129
# Тюменская_область EPSG:32642 / 140291 / N27505666
# Московская_область EPSG:32637 / 51490 / N1686293227

In [4]:
region_name = 'Ленинградская_область'
local_crs = 32636
geocode = 176095
region_capital = ox.geocode_to_gdf('N27025179',by_osmid=True)
city = ox.geocode_to_gdf(f'R{geocode}', by_osmid=True).to_crs(epsg=4326)
city['layer'] = region_name
city['status'] = 'region'

In [4]:
# Считывание входных данных

PLACEHOLDER = gpd.GeoDataFrame(geometry=[]) # если нет данных о сервисе

# полигоны районов и муниципальных образований
settlement = gpd.read_file(f'/Users/sashamorozov/Documents/НЦКР платформа ЦУ/Показатели по 9 регионам/data/data/{region_name}/{region_name}_settlement.geojson')
district = gpd.read_file(f'/Users/sashamorozov/Documents/НЦКР платформа ЦУ/Показатели по 9 регионам/data/data/{region_name}/{region_name}_district.geojson')

# населенные пункты и админ.центры точками
region_points = gpd.read_file(f'/Users/sashamorozov/Documents/НЦКР платформа ЦУ/Показатели по 9 регионам/data/data/{region_name}/{region_name}_region_points.geojson')
admin_centers = gpd.read_file(f'/Users/sashamorozov/Documents/НЦКР платформа ЦУ/Показатели по 9 регионам/data/data/{region_name}/{region_name}_district_admin_centres_18_nodes.geojson')
# либо:
# admin_centers = region_points[region_points['is_admin_centre_district']==True]


# Сервисы
railway_stations = gpd.read_file(f'/Users/sashamorozov/Documents/НЦКР платформа ЦУ/Показатели по 9 регионам/data/data/{region_name}/{region_name}_railway_stations.geojson')
railway_roads = gpd.read_file(f'/Users/sashamorozov/Documents/НЦКР платформа ЦУ/Показатели по 9 регионам/data/data/{region_name}/{region_name}_railway_roads.geojson')
bus_stops = gpd.read_file(f'/Users/sashamorozov/Documents/НЦКР платформа ЦУ/Показатели по 9 регионам/data/data/{region_name}/{region_name}_bus_stops.geojson')
bus_routes = gpd.read_file(f'/Users/sashamorozov/Documents/НЦКР платформа ЦУ/Показатели по 9 регионам/data/data/{region_name}/{region_name}_bus_routes.geojson')
fuel_stations = gpd.read_file(f'/Users/sashamorozov/Documents/НЦКР платформа ЦУ/Показатели по 9 регионам/data/data/{region_name}/{region_name}_fuel_stations.geojson')
# ferry_terminal = PLACEHOLDER
ferry_terminal = gpd.read_file(f'/Users/sashamorozov/Documents/НЦКР платформа ЦУ/Показатели по 9 регионам/data/data/{region_name}/{region_name}_ferry_terminal.geojson')
local_aerodrome = gpd.read_file(f'/Users/sashamorozov/Documents/НЦКР платформа ЦУ/Показатели по 9 регионам/data/data/{region_name}/{region_name}_local_aerodrome.geojson')
international_aerodrome = gpd.read_file(f'/Users/sashamorozov/Documents/НЦКР платформа ЦУ/Показатели по 9 регионам/data/data/{region_name}/{region_name}_international_aerodrome.geojson')
# либо:
# international_aerodrome = local_aerodrome[local_aerodrome['aerodrome:type']=='international']
# international_aerodrome['geometry'] = shapely.centroid(international_aerodrome['geometry']).set_crs(international_aerodrome.crs)

# Природные объекты
water = gpd.read_file(f'/Users/sashamorozov/Documents/НЦКР платформа ЦУ/Показатели по 9 регионам/data/data/{region_name}/{region_name}_water.geojson')
nature_reserve = gpd.read_file(f'/Users/sashamorozov/Documents/НЦКР платформа ЦУ/Показатели по 9 регионам/data/data/{region_name}/{region_name}_nature_reserve.geojson')

# Кастомная территория
custom_territory = gpd.read_file('/Users/sashamorozov/Documents/НЦКР платформа ЦУ/Показатели по 9 регионам/data/data/Ленинградская_область/project Светогорского поселения.geojson')
custom_territory_center = custom_territory.geometry.representative_point()
custom_territory_center = gpd.GeoDataFrame([{'geometry': custom_territory_center.iloc[0]}], crs=custom_territory_center.crs).to_crs(local_crs)

# Полигон РФ, необходим для построения транспортного каркаса
russia = ox.geocode_to_gdf("Russia") 
regions = gpd.read_file(f'/Users/sashamorozov/Documents/НЦКР платформа ЦУ/Показатели по 9 регионам/data/data/regions_of_russia.geojson') #  get regions
regions = regions[regions['ISO3166-2']!='RU-CHU']
regions = regions.to_crs(city.crs)

In [5]:
# Загрузка УДС графа из файла 

citygraph = nx.read_graphml(f'/Users/sashamorozov/Documents/НЦКР платформа ЦУ/Показатели по 9 регионам/data/graphs/{region_name}/{region_name}_uds.graphml')
citygraph = graphbuilder.convert_list_attr_from_str(citygraph)
citygraph = indicators.prepare_graph(citygraph)

In [6]:
# Загрузка интермодального графа из файла 

inter = nx.read_graphml(f'/Users/sashamorozov/Documents/НЦКР платформа ЦУ/Показатели по 9 регионам/data/graphs/{region_name}/{region_name}_inter.graphml')
inter = graphbuilder.convert_list_attr_from_str(inter)
inter = indicators.prepare_graph(inter)

In [6]:
citygraph_n,citygraph_e = momepy.nx_to_gdf(citygraph)

In [7]:
citygraph_e

,length_meter,geometry,type,time_sec,time_min,highway,maxspeed,reg,ref,is_exit,node_start,node_end
0,158.791,"LINESTRING (316822.012 6514139.318, 316864.213...",car,9.527,0.158783,tertiary,16.666667,3,NaN,0,0,1
1,209.104,"LINESTRING (316822.012 6514139.318, 316878.621...",car,12.546,0.209100,tertiary,16.666667,3,NaN,0,0,2
2,109.356,"LINESTRING (316822.012 6514139.318, 316793.074...",car,6.561,0.109350,tertiary,16.666667,3,NaN,0,0,3
3,178.371,"LINESTRING (316822.012 6514139.318, 316821.070...",car,10.702,0.178367,residential,16.666667,3,NaN,0,0,4
4,166.563,"LINESTRING (316864.213 6514292.399, 316905.768...",car,9.994,0.166567,tertiary,16.666667,3,NaN,0,1,284
...,...,...,...,...,...,...,...,...,...,...,...,...
313586,42.975,"LINESTRING (222429.409 6727810.800, 222434.555...",car,2.579,0.042983,unclassified,16.666667,3,NaN,0,126390,126391
313587,443.462,"LINESTRING (222453.684 6727777.907, 222478.142...",car,26.608,0.443467,unclassified,16.666667,3,NaN,0,126391,126391
313588,443.462,"LINESTRING (222453.684 6727777.907, 222468.710...",car,26.608,0.443467,unclassified,16.666667,3,NaN,0,126391,126391
313589,42.975,"LINESTRING (222453.684 6727777.907, 222434.555...",car,2.579,0.042983,unclassified,16.666667,3,NaN,0,126391,126390
313590,2912.574,"LINESTRING (219440.802 6729630.100, 219460.016...",car,116.503,1.941717,trunk,25.000000,1,"[А-181, 7]",1,126392,126383

In [10]:
citygraph_n

,reg_1,reg_2,x,y,nodeID,exit,exit_country,geometry
0,False,False,316822.011829,6.514139e+06,0,NaN,NaN,POINT (316822.012 6514139.318)
1,False,False,316864.213100,6.514292e+06,1,NaN,NaN,POINT (316864.213 6514292.399)
2,False,False,317015.043435,6.514061e+06,2,NaN,NaN,POINT (317015.043 6514060.895)
3,False,False,316716.593408,6.514168e+06,3,NaN,NaN,POINT (316716.593 6514168.399)
4,False,False,316771.697024,6.513968e+06,4,NaN,NaN,POINT (316771.697 6513968.255)
...,...,...,...,...,...,...,...,...
126388,False,False,222720.907545,6.728057e+06,126388,NaN,NaN,POINT (222720.908 6728057.151)
126389,False,False,222481.292591,6.728106e+06,126389,NaN,NaN,POINT (222481.293 6728106.467)
126390,False,False,222429.409497,6.727811e+06,126390,NaN,NaN,POINT (222429.409 6727810.800)
126391,False,False,222453.683954,6.727778e+06,126391,NaN,NaN,POINT (222453.684 6727777.907)
126392,True,False,219440.802094,6.729630e+06,126392,1.0,1.0,POINT (219440.802 6729630.100)

In [8]:
services = {
    'railway_stops' : railway_stations, # ЖД остановки
    'fuel' : fuel_stations, # АЗС станции
    'ports' : ferry_terminal, # Порты
    'local_aero' : local_aerodrome, # Аэропорты местного значения
    'international_aero' : international_aerodrome, # Аэропорты международного значения
    'oopt' : nature_reserve, # Особо охраняемые природные объекты
    'water_objects' : water, # Водные объекты
    'train_paths' : railway_roads, # ЖД пути
    'bus_stops' : bus_stops, # Автобусные остановки 
    'capital': region_capital, # Столица региона (точка)
    'points': region_points, # Населенные пункты региона (точки)
    'bus_routes' : bus_routes, # Автобусные маршруты
    'region_centers': admin_centers, # Административные центры муниципальных районов региона (точки)
    'neud_center': custom_territory_center # Центроида полигона кастомной территории (территория+3 км буфер)
}

In [9]:
G = indicators.assign_services_names_to_nodes(services,citygraph_n,citygraph,crs = local_crs)

railway_stops
fuel
ports
local_aero
international_aero
no oopt (((((((
no water_objects (((((((
no train_paths (((((((
bus_stops
capital
points
bus_routes
region_centers
neud_center

In [10]:
# Вычисление показателей на 3 уровнях: регион, районы, муниципальные образования

merged = indicators.indicator_area(G,inter,services,[city,district,settlement],local_crs)

100%|██████████| 2834/2834 [21:40<00:00,  2.18it/s]

new version
new version

/Users/sashamorozov/Documents/Code/NCCR/transport_frames/transport_frames/src/metrics/indicators.py:779: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  merged[cols_to_format] = merged[cols_to_format].applymap(
/Users/sashamorozov/Documents/Code/NCCR/transport_frames/transport_frames/src/metrics/indicators.py:779: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  merged[cols_to_format] = merged[cols_to_format].applymap(
/Users/sashamorozov/Documents/Code/NCCR/transport_frames/transport_frames/src/metrics/indicators.py:779: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  merged[cols_to_format] = merged[cols_to_format].applymap(

In [11]:
merged[0]

,index,name,status,layer,geometry,fuel_stations_accessibility,train_stops_accessibility,local_aero_accessibility,international_aero_accessibility,ports_accessibility,...,number_of_fuel_stations,number_of_train_stops,number_of_local_aero,number_of_international_aero,number_of_ports,number_of_bus_stops,reg1_length,reg2_length,reg3_length,number_of_bus_routes
0,0,Leningrad Oblast,region,Ленинградская_область,"MULTIPOLYGON (((26.44000 59.93833, 26.62887 59...",15.785,14.734,37.600,130.785,124.930,...,196.000,573.000,28.000,0.000,2.000,8332.000,3906.095,19235.816,51217.282,540.000

In [12]:
merged[1]

,index,name,status,layer,geometry,fuel_stations_accessibility,train_stops_accessibility,local_aero_accessibility,international_aero_accessibility,ports_accessibility,...,number_of_fuel_stations,number_of_train_stops,number_of_local_aero,number_of_international_aero,number_of_ports,number_of_bus_stops,reg1_length,reg2_length,reg3_length,number_of_bus_routes
0,0,Бокситогорский муниципальный район,district,Бокситогорский муниципальный район,"MULTIPOLYGON (((34.32834 59.19564, 34.32777 59...",21.627,22.698,107.019,353.314,258.178,...,11.000,20.000,0.000,0.000,0.000,363.000,225.035,1040.889,1896.486,31.000
1,1,Кингисеппский муниципальный район,district,Кингисеппский муниципальный район,"MULTIPOLYGON (((26.67752 59.96863, 26.67743 59...",14.805,29.220,25.887,118.252,158.175,...,18.000,10.000,3.000,0.000,0.000,567.000,266.679,1151.417,1844.225,47.000
2,2,Киришский муниципальный район,district,Киришский муниципальный район,"MULTIPOLYGON (((31.94177 59.42479, 31.94327 59...",17.497,7.809,37.923,180.318,138.161,...,8.000,24.000,2.000,0.000,0.000,298.000,0.000,739.883,1144.122,31.000
3,3,Кировский муниципальный район,district,Кировский муниципальный район,"MULTIPOLYGON (((31.91715 59.95987, 31.91722 59...",12.529,7.196,31.776,66.890,38.349,...,6.000,52.000,1.000,0.000,0.000,308.000,167.648,763.931,3924.791,47.000
4,4,Лодейнопольский муниципальный район,district,Лодейнопольский муниципальный район,"MULTIPOLYGON (((32.95801 60.71431, 33.02438 60...",19.728,26.779,88.491,192.750,53.330,...,6.000,14.000,0.000,0.000,1.000,143.000,221.498,769.354,992.355,25.000
5,5,Ломоносовский муниципальный район,district,Ломоносовский муниципальный район,"MULTIPOLYGON (((28.84956 59.78505, 28.84950 59...",6.684,21.430,19.964,29.287,65.666,...,14.000,6.000,3.000,0.000,0.000,502.000,184.593,857.339,3829.328,64.000
6,6,Подпорожский муниципальный район,district,Подпорожский муниципальный район,"MULTIPOLYGON (((35.52906 60.91530, 35.52806 60...",47.117,76.328,27.703,251.322,86.706,...,3.000,8.000,2.000,0.000,0.000,196.000,201.018,867.178,1216.647,21.000
7,7,Приозерский муниципальный район,district,Приозерский муниципальный район,"MULTIPOLYGON (((30.69201 60.50326, 30.68940 60...",24.685,11.646,39.943,127.052,125.070,...,3.000,26.000,2.000,0.000,0.000,478.000,289.733,1266.637,3449.656,41.000
8,8,Сосновоборский городской округ,district,Сосновоборский городской округ,"MULTIPOLYGON (((28.97562 59.81609, 28.97583 59...",3.744,7.364,50.067,88.282,124.662,...,7.000,2.000,0.000,0.000,0.000,154.000,0.000,72.746,508.558,21.000
9,9,Волосовский муниципальный район,district,Волосовский муниципальный район,"MULTIPOLYGON (((28.98894 59.48069, 28.98604 59...",17.710,13.933,15.183,103.699,134.692,...,2.000,14.000,3.000,0.000,0.000,289.000,81.009,995.070,1098.220,32.000
10,10,Волховский муниципальный район,district,Волховский муниципальный район,"MULTIPOLYGON (((32.85314 60.51175, 32.84899 60...",12.710,12.649,66.861,136.033,95.708,...,15.000,67.000,0.000,0.000,0.000,344.000,291.351,1202.621,2795.222,37.000
11,11,Всеволожский муниципальный район,district,Всеволожский муниципальный район,"MULTIPOLYGON (((30.55161 59.96981, 30.55200 59...",8.375,4.968,24.944,39.236,39.490,...,26.000,69.000,2.000,0.000,0.000,1044.000,432.772,1115.782,8619.117,96.000
12,12,Выборгский муниципальный район,district,Выборгский муниципальный район,"MULTIPOLYGON (((27.64248 60.20397, 27.64231 60...",19.675,9.193,46.722,101.180,126.316,...,20.000,80.000,2.000,0.000,0.000,886.000,516.246,2558.977,6780.242,70.000
13,13,Гатчинский муниципальный район,district,Гатчинский муниципальный район,"MULTIPOLYGON (((29.63489 59.57073, 29.63372 59...",12.214,6.559,16.722,62.236,85.391,...,12.000,73.000,2.000,0.000,0.000,878.000,242.969,1160.768,5035.923,60.000
14,14,Лужский муниципальный район,district,Лужский муниципальный район,"MULTIPOLYGON (((29.74752 58.43696, 29.74807 58...",19.665,16.369,34.302,147.220,166.606,...,11.000,30.000,4.000,0.000,0.000,720.000,236.638,1557.359,3471.695,49.000
15,15,Сланцевский муниципальный район,district,Сланцевский муниципальный район,"MULTIPOLYGON (((28.55918 59.15314, 28.55977 59...",17.226,30.479,62.601,189.064,237.994,...,7.000,4.000,0.000,0.000,0.000,309.000,0.000,926.944,598.817,36.000
16,16,Тихвинский муниципальный район,district,Тихвинский муниципальный район,"MULTIPOLYGON (((34.40706 60.15749, 34.40750 60...",21.377,44.117,44.708,266.805,150.941,...,7.000,25.000,1.000,0.000,0.000,315.000,100.035,1125.688,1246.197,55.000
17,17,Тосненский муниципальный район,district,Тосненский муниципальный район,"MULTIPOLYGON (((30.68185 59.72645, 30.68152 59...",13.387,8.707,40.798,63.230,64.434,...,20.000,49.000,1.000,0.000,0.000,538.000,451.618,1064.090,2762.003,39.000

In [13]:
merged[2]

,index,name,status,layer,geometry,fuel_stations_accessibility,train_stops_accessibility,local_aero_accessibility,international_aero_accessibility,ports_accessibility,...,number_of_fuel_stations,number_of_train_stops,number_of_local_aero,number_of_international_aero,number_of_ports,number_of_bus_stops,reg1_length,reg2_length,reg3_length,number_of_bus_routes
0,0,Самойловское сельское поселение,settlement,Бокситогорский муниципальный район,"MULTIPOLYGON (((34.42169 59.68391, 34.42428 59...",22.624,22.569,99.553,345.849,248.458,...,2.000,2.000,0.000,0.000,0.000,68.000,36.919,181.873,205.642,12.000
1,1,Большедворское сельское поселение,settlement,Бокситогорский муниципальный район,"MULTIPOLYGON (((34.30682 59.71494, 34.30791 59...",19.907,13.453,57.849,310.735,217.430,...,1.000,8.000,0.000,0.000,0.000,50.000,64.648,136.049,209.508,16.000
2,2,Пикалевское городское поселение,settlement,Бокситогорский муниципальный район,"MULTIPOLYGON (((34.14251 59.48759, 34.13616 59...",1.257,6.315,92.884,339.179,241.789,...,2.000,1.000,0.000,0.000,0.000,59.000,28.911,17.084,157.384,20.000
3,3,Борское сельское поселение,settlement,Бокситогорский муниципальный район,"MULTIPOLYGON (((34.05997 59.15087, 34.06007 59...",15.474,28.700,35.159,278.639,254.760,...,1.000,0.000,0.000,0.000,0.000,44.000,0.000,168.191,121.404,12.000
4,4,Бокситогорское городское поселение,settlement,Бокситогорский муниципальный район,"MULTIPOLYGON (((34.06836 59.40315, 34.05535 59...",7.150,14.751,22.768,266.248,231.662,...,2.000,0.000,0.000,0.000,0.000,34.000,14.194,29.462,242.323,15.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,183,Фёдоровское городское поселение,settlement,Тосненский муниципальный район,"MULTIPOLYGON (((30.52049 59.69087, 30.52316 59...",14.623,8.998,41.984,31.814,58.632,...,0.000,2.000,0.000,0.000,0.000,21.000,0.000,29.765,241.837,3.000
184,184,Нурминское сельское поселение,settlement,Тосненский муниципальный район,"MULTIPOLYGON (((31.01271 59.63362, 31.01394 59...",8.090,1.242,67.055,49.312,59.119,...,0.000,2.000,0.000,0.000,0.000,15.000,0.000,44.134,143.887,4.000
185,185,Красноборское городское поселение,settlement,Тосненский муниципальный район,"MULTIPOLYGON (((30.58336 59.64993, 30.58367 59...",7.559,4.353,61.498,32.936,49.252,...,1.000,2.000,0.000,0.000,0.000,29.000,29.583,34.518,211.955,3.000
186,186,Трубникоборское сельское поселение,settlement,Тосненский муниципальный район,"MULTIPOLYGON (((31.13126 59.08942, 31.13522 59...",7.097,9.905,22.373,96.407,96.714,...,4.000,7.000,0.000,0.000,0.000,44.000,77.283,163.907,231.728,4.000
187,187,Лисинское сельское поселение,settlement,Тосненский муниципальный район,"MULTIPOLYGON (((30.59799 59.48382, 30.59899 59...",28.751,10.903,63.809,64.291,88.381,...,0.000,9.000,0.000,0.000,0.000,41.000,0.000,204.598,205.298,3.000

In [19]:
merged[2].to_parquet('Ленинградская_область_settlement.parquet', index=False)

In [8]:
# Вычисление показателей на уровне подаваемой территории+3км

temp = indicators.indicator_territory(G,custom_territory,local_crs,district,region_points,admin_centers,services,citygraph_n,citygraph_e)
temp

100%|██████████| 1/1 [00:00<00:00,  2.15it/s]
/Users/sashamorozov/Documents/Code/NCCR/transport_frames/transport_frames/src/metrics/indicators.py:871: UserWarning: Geometry is in a geographic CRS. Results from 'buffer' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  filtered_region_centers = region_centers[region_centers.buffer(0.1).intersects(filtered_regions_terr.unary_union)]
/Users/sashamorozov/Documents/Code/NCCR/transport_frames/transport_frames/src/metrics/indicators.py:872: UserWarning: Geometry is in a geographic CRS. Results from 'buffer' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  filtered_settlement_centers = points[points.buffer(0.1).intersects(filtered_regions_terr.unary_union)]

nearest_region_centers
nearest_settlement_centers

,name,to_region_admin_center,to_reg1,fuel_stations_accessibility,train_stops_accessibility,local_aero_accessibility,international_aero_accessibility,ports_accessibility,water_objects_accessibility,oopt_accessibility,...,number_of_international_aero,number_of_bus_stops,number_of_water_objects,number_of_oopt,density,train_path_length,number_of_bus_routes,to_nearest_settlement_center,to_nearest_mo_center,geometry
17950,None,223.144,5.102,7.097,45.651,107.438,172.108,197.244,0.032,0.268,...,0,0,1,0,1631.604,0.0,39,5065.79,57079.076,"POLYGON ((28.88155 61.13215, 28.91140 61.11113..."